
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.ScrolledWindow scrolledwindow3;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Notebook notebook3;

	private global::Gtk.Table table3;

	private global::Gtk.ComboBoxEntry cmbeCatIdcateg;

	private global::Gtk.ComboBoxEntry cmbeCatIdEncar;

	private global::Gtk.ComboBoxEntry cmbeCatIdplato;

	private global::Gtk.Entry entCatDesc;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label26;

	private global::Gtk.Table table2;

	private global::Gtk.ComboBoxEntry cmbeEncid;

	private global::Gtk.Entry entApellido;

	private global::Gtk.Entry entNombre;

	private global::Gtk.Label label10;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Label label27;

	private global::Gtk.Table table5;

	private global::Gtk.ComboBoxEntry cmbeIngid;

	private global::Gtk.Entry entalmacen;

	private global::Gtk.Entry entingrediente;

	private global::Gtk.Entry entunidad;

	private global::Gtk.Label label11;

	private global::Gtk.Label label12;

	private global::Gtk.Label label13;

	private global::Gtk.Label label14;

	private global::Gtk.Label label28;

	private global::Gtk.Table table6;

	private global::Gtk.ComboBoxEntry cmbePlatilloId;

	private global::Gtk.ComboBoxEntry cmbePlatilloidplato;

	private global::Gtk.Entry entDescripcion;

	private global::Gtk.Entry entnivel;

	private global::Gtk.Label label17;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Label label20;

	private global::Gtk.Label label29;

	private global::Gtk.Table table7;

	private global::Gtk.Button btnFoto;

	private global::Gtk.ComboBoxEntry cmbePlatId;

	private global::Gtk.Entry entprecio;

	private global::Gtk.Label label32;

	private global::Gtk.Label label33;

	private global::Gtk.Label label34;

	private global::Gtk.Label label30;

	private global::Gtk.Table table8;

	private global::Gtk.ComboBoxEntry cmbeUtilidIngred;

	private global::Gtk.ComboBoxEntry cmbeUtilidPlat;

	private global::Gtk.Entry entcant;

	private global::Gtk.Label label35;

	private global::Gtk.Label label36;

	private global::Gtk.Label label37;

	private global::Gtk.Label label31;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Table table1;

	private global::Gtk.Button btnComp;

	private global::Gtk.Button btnDesconectar;

	private global::Gtk.Button btnInsertar;

	private global::Gtk.Button btnSalir;

	private global::Gtk.Label GtkLabel4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "stock_search-and-replace", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow3.CanFocus = true;
		this.scrolledwindow3.Name = "scrolledwindow3";
		this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow3.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.notebook3 = new global::Gtk.Notebook();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 0;
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.table3 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.cmbeCatIdcateg = global::Gtk.ComboBoxEntry.NewText();
		this.cmbeCatIdcateg.Name = "cmbeCatIdcateg";
		this.table3.Add(this.cmbeCatIdcateg);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.cmbeCatIdcateg]));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.cmbeCatIdEncar = global::Gtk.ComboBoxEntry.NewText();
		this.cmbeCatIdEncar.Name = "cmbeCatIdEncar";
		this.table3.Add(this.cmbeCatIdEncar);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.cmbeCatIdEncar]));
		w3.TopAttach = ((uint)(3));
		w3.BottomAttach = ((uint)(4));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.cmbeCatIdplato = global::Gtk.ComboBoxEntry.NewText();
		this.cmbeCatIdplato.Name = "cmbeCatIdplato";
		this.table3.Add(this.cmbeCatIdplato);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.cmbeCatIdplato]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entCatDesc = new global::Gtk.Entry();
		this.entCatDesc.CanFocus = true;
		this.entCatDesc.Name = "entCatDesc";
		this.entCatDesc.IsEditable = true;
		this.entCatDesc.InvisibleChar = '•';
		this.table3.Add(this.entCatDesc);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.entCatDesc]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("id_categoria");
		this.table3.Add(this.label4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.label4]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("id_plato");
		this.table3.Add(this.label5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.label5]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion");
		this.table3.Add(this.label6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.label6]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("id_encargado");
		this.table3.Add(this.label7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
		w9.TopAttach = ((uint)(3));
		w9.BottomAttach = ((uint)(4));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook3.Add(this.table3);
		// Notebook tab
		this.label26 = new global::Gtk.Label();
		this.label26.Name = "label26";
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Categoria");
		this.notebook3.SetTabLabel(this.table3, this.label26);
		this.label26.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.cmbeEncid = global::Gtk.ComboBoxEntry.NewText();
		this.cmbeEncid.Name = "cmbeEncid";
		this.table2.Add(this.cmbeEncid);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2[this.cmbeEncid]));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entApellido = new global::Gtk.Entry();
		this.entApellido.CanFocus = true;
		this.entApellido.Name = "entApellido";
		this.entApellido.IsEditable = true;
		this.entApellido.InvisibleChar = '•';
		this.table2.Add(this.entApellido);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.entApellido]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entNombre = new global::Gtk.Entry();
		this.entNombre.CanFocus = true;
		this.entNombre.Name = "entNombre";
		this.entNombre.IsEditable = true;
		this.entNombre.InvisibleChar = '•';
		this.table2.Add(this.entNombre);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2[this.entNombre]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
		this.table2.Add(this.label10);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.label10]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("id_encargado");
		this.table2.Add(this.label8);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.label8]));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
		this.table2.Add(this.label9);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2[this.label9]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook3.Add(this.table2);
		global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.table2]));
		w17.Position = 1;
		// Notebook tab
		this.label27 = new global::Gtk.Label();
		this.label27.Name = "label27";
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Encargado");
		this.notebook3.SetTabLabel(this.table2, this.label27);
		this.label27.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.table5 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.cmbeIngid = global::Gtk.ComboBoxEntry.NewText();
		this.cmbeIngid.Name = "cmbeIngid";
		this.table5.Add(this.cmbeIngid);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table5[this.cmbeIngid]));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.entalmacen = new global::Gtk.Entry();
		this.entalmacen.CanFocus = true;
		this.entalmacen.Name = "entalmacen";
		this.entalmacen.IsEditable = true;
		this.entalmacen.InvisibleChar = '•';
		this.table5.Add(this.entalmacen);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table5[this.entalmacen]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.entingrediente = new global::Gtk.Entry();
		this.entingrediente.CanFocus = true;
		this.entingrediente.Name = "entingrediente";
		this.entingrediente.IsEditable = true;
		this.entingrediente.InvisibleChar = '•';
		this.table5.Add(this.entingrediente);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table5[this.entingrediente]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.entunidad = new global::Gtk.Entry();
		this.entunidad.CanFocus = true;
		this.entunidad.Name = "entunidad";
		this.entunidad.IsEditable = true;
		this.entunidad.InvisibleChar = '•';
		this.table5.Add(this.entunidad);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table5[this.entunidad]));
		w21.TopAttach = ((uint)(3));
		w21.BottomAttach = ((uint)(4));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("id_ingrediente");
		this.table5.Add(this.label11);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table5[this.label11]));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrediente");
		this.table5.Add(this.label12);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table5[this.label12]));
		w23.TopAttach = ((uint)(1));
		w23.BottomAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("almacen");
		this.table5.Add(this.label13);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table5[this.label13]));
		w24.TopAttach = ((uint)(2));
		w24.BottomAttach = ((uint)(3));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Unidad");
		this.table5.Add(this.label14);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table5[this.label14]));
		w25.TopAttach = ((uint)(3));
		w25.BottomAttach = ((uint)(4));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook3.Add(this.table5);
		global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.table5]));
		w26.Position = 2;
		// Notebook tab
		this.label28 = new global::Gtk.Label();
		this.label28.Name = "label28";
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrediente");
		this.notebook3.SetTabLabel(this.table5, this.label28);
		this.label28.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.table6 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
		this.table6.Name = "table6";
		this.table6.RowSpacing = ((uint)(6));
		this.table6.ColumnSpacing = ((uint)(6));
		// Container child table6.Gtk.Table+TableChild
		this.cmbePlatilloId = global::Gtk.ComboBoxEntry.NewText();
		this.cmbePlatilloId.Name = "cmbePlatilloId";
		this.table6.Add(this.cmbePlatilloId);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table6[this.cmbePlatilloId]));
		w27.LeftAttach = ((uint)(1));
		w27.RightAttach = ((uint)(2));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.cmbePlatilloidplato = global::Gtk.ComboBoxEntry.NewText();
		this.cmbePlatilloidplato.Name = "cmbePlatilloidplato";
		this.table6.Add(this.cmbePlatilloidplato);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table6[this.cmbePlatilloidplato]));
		w28.TopAttach = ((uint)(1));
		w28.BottomAttach = ((uint)(2));
		w28.LeftAttach = ((uint)(1));
		w28.RightAttach = ((uint)(2));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.entDescripcion = new global::Gtk.Entry();
		this.entDescripcion.CanFocus = true;
		this.entDescripcion.Name = "entDescripcion";
		this.entDescripcion.IsEditable = true;
		this.entDescripcion.InvisibleChar = '•';
		this.table6.Add(this.entDescripcion);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table6[this.entDescripcion]));
		w29.TopAttach = ((uint)(2));
		w29.BottomAttach = ((uint)(3));
		w29.LeftAttach = ((uint)(1));
		w29.RightAttach = ((uint)(2));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.entnivel = new global::Gtk.Entry();
		this.entnivel.CanFocus = true;
		this.entnivel.Name = "entnivel";
		this.entnivel.IsEditable = true;
		this.entnivel.InvisibleChar = '•';
		this.table6.Add(this.entnivel);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table6[this.entnivel]));
		w30.TopAttach = ((uint)(3));
		w30.BottomAttach = ((uint)(4));
		w30.LeftAttach = ((uint)(1));
		w30.RightAttach = ((uint)(2));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("id_platillo");
		this.table6.Add(this.label17);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table6[this.label17]));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("id_plato");
		this.table6.Add(this.label18);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table6[this.label18]));
		w32.TopAttach = ((uint)(1));
		w32.BottomAttach = ((uint)(2));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion");
		this.table6.Add(this.label19);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table6[this.label19]));
		w33.TopAttach = ((uint)(2));
		w33.BottomAttach = ((uint)(3));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("nivel");
		this.table6.Add(this.label20);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table6[this.label20]));
		w34.TopAttach = ((uint)(3));
		w34.BottomAttach = ((uint)(4));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook3.Add(this.table6);
		global::Gtk.Notebook.NotebookChild w35 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.table6]));
		w35.Position = 3;
		// Notebook tab
		this.label29 = new global::Gtk.Label();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("platillo");
		this.notebook3.SetTabLabel(this.table6, this.label29);
		this.label29.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.table7 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table7.Name = "table7";
		this.table7.RowSpacing = ((uint)(6));
		this.table7.ColumnSpacing = ((uint)(6));
		// Container child table7.Gtk.Table+TableChild
		this.btnFoto = new global::Gtk.Button();
		this.btnFoto.CanFocus = true;
		this.btnFoto.Name = "btnFoto";
		this.btnFoto.UseUnderline = true;
		this.btnFoto.Label = global::Mono.Unix.Catalog.GetString("Foto");
		this.table7.Add(this.btnFoto);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table7[this.btnFoto]));
		w36.TopAttach = ((uint)(1));
		w36.BottomAttach = ((uint)(2));
		w36.LeftAttach = ((uint)(1));
		w36.RightAttach = ((uint)(2));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.cmbePlatId = global::Gtk.ComboBoxEntry.NewText();
		this.cmbePlatId.Name = "cmbePlatId";
		this.table7.Add(this.cmbePlatId);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table7[this.cmbePlatId]));
		w37.LeftAttach = ((uint)(1));
		w37.RightAttach = ((uint)(2));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.entprecio = new global::Gtk.Entry();
		this.entprecio.CanFocus = true;
		this.entprecio.Name = "entprecio";
		this.entprecio.IsEditable = true;
		this.entprecio.InvisibleChar = '•';
		this.table7.Add(this.entprecio);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table7[this.entprecio]));
		w38.TopAttach = ((uint)(2));
		w38.BottomAttach = ((uint)(3));
		w38.LeftAttach = ((uint)(1));
		w38.RightAttach = ((uint)(2));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label32 = new global::Gtk.Label();
		this.label32.Name = "label32";
		this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("id_plato");
		this.table7.Add(this.label32);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table7[this.label32]));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label33 = new global::Gtk.Label();
		this.label33.Name = "label33";
		this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("Foto");
		this.table7.Add(this.label33);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table7[this.label33]));
		w40.TopAttach = ((uint)(1));
		w40.BottomAttach = ((uint)(2));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label34 = new global::Gtk.Label();
		this.label34.Name = "label34";
		this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("Precio");
		this.table7.Add(this.label34);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table7[this.label34]));
		w41.TopAttach = ((uint)(2));
		w41.BottomAttach = ((uint)(3));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook3.Add(this.table7);
		global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.table7]));
		w42.Position = 4;
		// Notebook tab
		this.label30 = new global::Gtk.Label();
		this.label30.Name = "label30";
		this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Plato");
		this.notebook3.SetTabLabel(this.table7, this.label30);
		this.label30.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.table8 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table8.Name = "table8";
		this.table8.RowSpacing = ((uint)(6));
		this.table8.ColumnSpacing = ((uint)(6));
		// Container child table8.Gtk.Table+TableChild
		this.cmbeUtilidIngred = global::Gtk.ComboBoxEntry.NewText();
		this.cmbeUtilidIngred.Name = "cmbeUtilidIngred";
		this.table8.Add(this.cmbeUtilidIngred);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table8[this.cmbeUtilidIngred]));
		w43.TopAttach = ((uint)(1));
		w43.BottomAttach = ((uint)(2));
		w43.LeftAttach = ((uint)(1));
		w43.RightAttach = ((uint)(2));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.cmbeUtilidPlat = global::Gtk.ComboBoxEntry.NewText();
		this.cmbeUtilidPlat.Name = "cmbeUtilidPlat";
		this.table8.Add(this.cmbeUtilidPlat);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table8[this.cmbeUtilidPlat]));
		w44.LeftAttach = ((uint)(1));
		w44.RightAttach = ((uint)(2));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.entcant = new global::Gtk.Entry();
		this.entcant.CanFocus = true;
		this.entcant.Name = "entcant";
		this.entcant.IsEditable = true;
		this.entcant.InvisibleChar = '•';
		this.table8.Add(this.entcant);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table8[this.entcant]));
		w45.TopAttach = ((uint)(2));
		w45.BottomAttach = ((uint)(3));
		w45.LeftAttach = ((uint)(1));
		w45.RightAttach = ((uint)(2));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.label35 = new global::Gtk.Label();
		this.label35.Name = "label35";
		this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("id_plato");
		this.table8.Add(this.label35);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table8[this.label35]));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.label36 = new global::Gtk.Label();
		this.label36.Name = "label36";
		this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("id_ingrediente");
		this.table8.Add(this.label36);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table8[this.label36]));
		w47.TopAttach = ((uint)(1));
		w47.BottomAttach = ((uint)(2));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.label37 = new global::Gtk.Label();
		this.label37.Name = "label37";
		this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("cantidad");
		this.table8.Add(this.label37);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table8[this.label37]));
		w48.TopAttach = ((uint)(2));
		w48.BottomAttach = ((uint)(3));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook3.Add(this.table8);
		global::Gtk.Notebook.NotebookChild w49 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.table8]));
		w49.Position = 5;
		// Notebook tab
		this.label31 = new global::Gtk.Label();
		this.label31.Name = "label31";
		this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Utiliza");
		this.notebook3.SetTabLabel(this.table8, this.label31);
		this.label31.ShowAll();
		this.fixed3.Add(this.notebook3);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.notebook3]));
		w50.X = 16;
		w50.Y = 9;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(1)), ((uint)(4)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.btnComp = new global::Gtk.Button();
		this.btnComp.CanFocus = true;
		this.btnComp.Name = "btnComp";
		this.btnComp.UseUnderline = true;
		this.btnComp.Label = global::Mono.Unix.Catalog.GetString("Conectar");
		this.table1.Add(this.btnComp);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1[this.btnComp]));
		w51.LeftAttach = ((uint)(1));
		w51.RightAttach = ((uint)(2));
		w51.XOptions = ((global::Gtk.AttachOptions)(4));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btnDesconectar = new global::Gtk.Button();
		this.btnDesconectar.CanFocus = true;
		this.btnDesconectar.Name = "btnDesconectar";
		this.btnDesconectar.UseUnderline = true;
		this.btnDesconectar.Label = global::Mono.Unix.Catalog.GetString("Desconectar");
		this.table1.Add(this.btnDesconectar);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1[this.btnDesconectar]));
		w52.LeftAttach = ((uint)(2));
		w52.RightAttach = ((uint)(3));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btnInsertar = new global::Gtk.Button();
		this.btnInsertar.CanFocus = true;
		this.btnInsertar.Name = "btnInsertar";
		this.btnInsertar.UseUnderline = true;
		this.btnInsertar.Label = global::Mono.Unix.Catalog.GetString("Insertar");
		this.table1.Add(this.btnInsertar);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1[this.btnInsertar]));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btnSalir = new global::Gtk.Button();
		this.btnSalir.CanFocus = true;
		this.btnSalir.Name = "btnSalir";
		this.btnSalir.UseUnderline = true;
		this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.table1.Add(this.btnSalir);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSalir]));
		w54.LeftAttach = ((uint)(3));
		w54.RightAttach = ((uint)(4));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add(this.table1);
		this.frame2.Add(this.GtkAlignment);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Botones</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel4;
		this.fixed3.Add(this.frame2);
		global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.frame2]));
		w57.X = 12;
		w57.Y = 295;
		w1.Add(this.fixed3);
		this.scrolledwindow3.Add(w1);
		this.Add(this.scrolledwindow3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 583;
		this.DefaultHeight = 395;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.notebook3.ChangeCurrentPage += new global::Gtk.ChangeCurrentPageHandler(this.note3_changecurrentpage);
		this.notebook3.SwitchPage += new global::Gtk.SwitchPageHandler(this.note3_SwitchPage);
		this.btnFoto.Clicked += new global::System.EventHandler(this.Foto_clicked);
		this.btnSalir.Clicked += new global::System.EventHandler(this.Salir);
		this.btnInsertar.Clicked += new global::System.EventHandler(this.btnInsertar_insertar);
		this.btnDesconectar.Clicked += new global::System.EventHandler(this.btnDesco_desconectar);
		this.btnComp.Clicked += new global::System.EventHandler(this.comprobar_clicked);
	}
}
